environment: development
debug: true

server:
  port: "8080"
  host: "localhost"
  log_level: "debug"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  name: "mini_seller_dev"
  ssl_mode: "disable"