services:
  mini-seller:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MINI_SELLER_REDIS_HOST=redis
      - MINI_SELLER_SERVER_HOST=0.0.0.0
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"