environment: development

server:
  host: 0.0.0.0
  port: 8080
  read_timeout_ms: 5000
  write_timeout_ms: 10000
  shutdown_timeout_ms: 30000
  health_check_timeout_ms: 5000
  idle_conn_timeout_ms: 90000
  worker_stop_timeout_ms: 5000

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  pool_timeout_ms: 4000
  idle_timeout_ms: 300000
  idle_check_frequency_ms: 60000

debug: true

rate_limit:
  qps: 100
  burst: 200

rate_limiting:
  requests_per_second: 100
  burst_size: 200

logging:
  level: debug
  format: json

buyers:
  - id: "buyer1"
    name: "Test Buyer 1"
    endpoint: "http://localhost:9001/bid"
    timeout_ms: 100
    qps: 50
  - id: "buyer2"
    name: "Test Buyer 2"
    endpoint: "http://localhost:9002/bid"
    timeout_ms: 100
    qps: 50

buyer:
  id: "default"
  name: "Default Buyer"
  endpoint: "http://localhost:9000/bid"
  timeout_ms: 100
  qps: 50