environment: development
debug: true

server:
  port: "8080"
  host: "localhost"
  log_level: "debug"
  read_timeout_ms: 5000
  write_timeout_ms: 10000
  shutdown_timeout_ms: 30000
  health_check_timeout_ms: 5000
  idle_conn_timeout_ms: 90000
  worker_stop_timeout_ms: 5000

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

logging:
  level: "debug"
  format: "text"

rate_limit:
  qps: 10.0
  burst: 20

buyers:
  - name: "buyer1"
    endpoint: "http://buyer1.local/bid"
    qps: 10.0
    burst: 20
    timeout_ms: 100