environment: development
debug: true

server:
  port: "8080"
  host: "localhost"
  log_level: "debug"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

logging:
  level: "debug"
  format: "text"

buyers:
  - name: "buyer1"
    endpoint: "http://buyer1.local/bid"
    qps: 10.0
    burst: 20
    timeout_ms: 100