environment: production
debug: false

server:
  port: "8080"
  host: "0.0.0.0"
  log_level: "info"
  read_timeout_ms: 3000
  write_timeout_ms: 5000
  shutdown_timeout_ms: 60000
  health_check_timeout_ms: 3000
  idle_conn_timeout_ms: 120000
  worker_stop_timeout_ms: 10000

redis:
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  password: "${REDIS_PASSWORD}"
  db: 0

logging:
  level: "info"
  format: "json"

rate_limit:
  qps: 50.0
  burst: 100

buyers:
  - name: "buyer1"
    endpoint: "${BUYER1_ENDPOINT}"
    qps: 15.0
    burst: 30
    timeout_ms: 100
  - name: "buyer2"
    endpoint: "${BUYER2_ENDPOINT}"
    qps: 20.0
    burst: 40
    timeout_ms: 150