environment: test
debug: true

server:
  port: "0"
  host: "localhost"
  log_level: "error"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 1

logging:
  level: "error"
  format: "text"

buyers: []